update: dev workflow

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -1,8 +1,8 @@
-name: Auto Merge, Build, and Deploy to Docker Hub 
+name: Auto Merge, Build, and Deploy to Docker Hub
 
 on:
   schedule:
-    - cron: '05 3 * * *'  # 매일 자정 00:00 (한국 시간, UTC+9 기준)
+    - cron: '05 15 * * *'  # 매일 00:05 (KST 기준)
   workflow_dispatch:  # 수동 실행 가능
 
 permissions:
@@ -43,25 +43,17 @@ jobs:
             echo "has_new_commits=true" >> $GITHUB_ENV
           fi
 
-      # 각 feat/* 브랜치의 변경 사항을 dev 브랜치로 PR 생성 또는 기존 PR 확인 후 병합
-      - name: Create or Find PRs from feat/* branches to dev
+      # 각 feat/* 브랜치의 변경 사항을 dev 브랜치로 PR 생성 및 병합
+      - name: Create or Merge PRs from feat/* branches to dev
         if: env.has_new_commits == 'true'
         env:
           GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
-          REACT_APP_KAKAO_CLIENT_ID: ${{ secrets.REACT_APP_KAKAO_CLIENT_ID }}
-          REACT_APP_KAKAO_AUTH_CODE_PATH: ${{ secrets.REACT_APP_KAKAO_AUTH_CODE_PATH }}
-          REACT_APP_KAKAO_REDIRECT_URI: ${{ secrets.REACT_APP_KAKAO_REDIRECT_URI }}
-          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
-          REACT_APP_GOOGLE_AUTH_CODE_PATH: ${{ secrets.REACT_APP_GOOGLE_AUTH_CODE_PATH }}
-          REACT_APP_GOOGLE_REDIRECT_URI: ${{ secrets.REACT_APP_GOOGLE_REDIRECT_URI }}
-          REACT_APP_GITHUB_CLIENT_ID: ${{ secrets.REACT_APP_GITHUB_CLIENT_ID }}
-          REACT_APP_GITHUB_AUTH_CODE_PATH: ${{ secrets.REACT_APP_GITHUB_AUTH_CODE_PATH }}
         run: |
-          echo "Attempting to create or find PRs from feat/* branches to dev."
+          echo "Attempting to create or merge PRs from feat/* branches to dev."
           git for-each-ref --format '%(refname:short)' refs/remotes/origin/feat/* | while read -r TARGET_BRANCH; do
             TARGET_BRANCH=${TARGET_BRANCH#origin/} # Remove 'origin/' prefix
             echo "Processing branch: $TARGET_BRANCH"
-            
+
             PR_URL=$(gh pr list --base dev --head "$TARGET_BRANCH" --json url --jq '.[0].url' || echo "")
             if [ -z "$PR_URL" ]; then
               PR_URL=$(gh pr create --base dev --head "$TARGET_BRANCH" --title "Auto merge $TARGET_BRANCH into dev" --body "자동 생성된 Pull Request" || echo "")
@@ -69,7 +61,9 @@ jobs:
             else
               echo "Existing PR found: $PR_URL"
             fi
-            echo "PR_URL=$PR_URL" >> $GITHUB_ENV
+
+            # PR 자동 병합
+            gh pr merge "$PR_URL" --squash --delete-branch --auto || echo "Merge failed for $TARGET_BRANCH"
           done
 
       # Docker 빌드 및 Docker Hub 푸시
@@ -81,29 +75,32 @@ jobs:
           password: ${{ secrets.DOCKER_PASSWORD }}
 
       - name: Build and push Docker image to Docker Hub
-        if: env.has_new_commits == 'true'
+        if: env.has_new_commits == 'true' && github.ref == 'refs/heads/dev'
         run: |
           git fetch origin dev
           git checkout dev
           git pull origin dev  # 최신 dev 브랜치 가져오기
-          
+
           # Docker 빌드
-          docker build -t narrativa_front . \
-            --build-arg REACT_APP_KAKAO_CLIENT_ID=$REACT_APP_KAKAO_CLIENT_ID \
-            --build-arg REACT_APP_KAKAO_AUTH_CODE_PATH=$REACT_APP_KAKAO_AUTH_CODE_PATH \
-            --build-arg REACT_APP_KAKAO_REDIRECT_URI=$REACT_APP_KAKAO_REDIRECT_URI \
-            --build-arg REACT_APP_GOOGLE_CLIENT_ID=$REACT_APP_GOOGLE_CLIENT_ID \
-            --build-arg REACT_APP_GOOGLE_AUTH_CODE_PATH=$REACT_APP_GOOGLE_AUTH_CODE_PATH \
-            --build-arg REACT_APP_GOOGLE_REDIRECT_URI=$REACT_APP_GOOGLE_REDIRECT_URI \
-            --build-arg REACT_APP_GITHUB_CLIENT_ID=$REACT_APP_GITHUB_CLIENT_ID \
-            --build-arg REACT_APP_GITHUB_AUTH_CODE_PATH=$REACT_APP_GITHUB_AUTH_CODE_PATH
-          docker tag narrativa_front:latest ${{ secrets.DOCKER_USERNAME }}/narrativa_front:latest
-          docker push ${{ secrets.DOCKER_USERNAME }}/narrativa_front:latest
+          export DOCKER_TAG=${{ secrets.DOCKER_USERNAME }}/narrativa_front:latest
+          docker build -t $DOCKER_TAG . \
+            --build-arg REACT_APP_KAKAO_CLIENT_ID=${{ secrets.REACT_APP_KAKAO_CLIENT_ID }} \
+            --build-arg REACT_APP_KAKAO_AUTH_CODE_PATH=${{ secrets.REACT_APP_KAKAO_AUTH_CODE_PATH }} \
+            --build-arg REACT_APP_KAKAO_REDIRECT_URI_PART=${{ secrets.REACT_APP_KAKAO_REDIRECT_URI_PART }} \
+            --build-arg REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }} \
+            --build-arg REACT_APP_GOOGLE_AUTH_CODE_PATH=${{ secrets.REACT_APP_GOOGLE_AUTH_CODE_PATH }} \
+            --build-arg REACT_APP_GOOGLE_REDIRECT_URI_PART=${{ secrets.REACT_APP_GOOGLE_REDIRECT_URI_PART }} \
+            --build-arg REACT_APP_GITHUB_CLIENT_ID=${{ secrets.REACT_APP_GITHUB_CLIENT_ID }} \
+            --build-arg REACT_APP_GITHUB_AUTH_CODE_PATH=${{ secrets.REACT_APP_GITHUB_AUTH_CODE_PATH }} \
+            --build-arg REACT_APP_URI=${{ secrets.REACT_APP_URI }} \
+            --build-arg REACT_APP_SPRING_URI=${{ secrets.REACT_APP_SPRING_URI }}
+
+          docker push $DOCKER_TAG
 
   deploy_local:
     runs-on: self-hosted
     needs: auto_merge_build_deploy
-    if: needs.auto_merge_build_deploy.outputs.has_new_commits == 'true'
+    if: needs.auto_merge_build_deploy.outputs.has_new_commits == 'true' && github.ref == 'refs/heads/dev'
     steps:
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
